export const pricingTiers = [
  {
    name: 'Free',
    price: 0,
    features: [
      'Limited surveys and respondents',
      'Basic question types',
      'Email verification',
      'Basic security features',
      'Limited reporting (Excel, CSV)',
    ],
    cta: 'Start for free',
    mostPopular: false,
  },
  {
    name: 'Basic',
    price: 49,
    features: [
      'Unlimited surveys & respondents',
      'Advanced question types and logic',
      'Email/SMS campaigns',
      'A/B testing',
      'Social media integration',
      'Custom email templates',
      'Enhanced reporting',
    ],
    cta: 'Start free trial',
    mostPopular: true,
  },
  {
    name: 'Advanced',
    price: 99,
    features: [
      'Full survey logic',
      'AI-generated questions',
      'Conversational questions',
      'Full reporting suite',
      'Multi-language (2 languages)',
      'SMS/Email with A/B testing',
      'TURF & NPS analysis',
    ],
    cta: 'Start free trial',
    mostPopular: false,
  },
  {
    name: 'Premium',
    price: 199,
    features: [
      'All features unlocked',
      'Unlimited users & languages',
      'Advanced integrations',
      'Dynamic real-time reporting',
      'Role-based access control',
      'Full API access',
      'GDPR compliance',
    ],
    cta: 'Contact sales',
    mostPopular: false,
  },
];